const eventLabels: Record<string, string> = {
  REQUEST_SUBMITTED: 'Solicitud recibida',
  JOB_CASE_CREATED: 'Expediente creado',
  CUSTOMER_REQUEST_CANCELLED: 'Solicitud cancelada',
  DOCUMENT_ADDED: 'Documento agregado',
  DOCUMENT_VERSION_ADDED: 'Nueva versión documental',
  DOCUMENT_REMOVED: 'Documento retirado',
  JOB_CASE_STATUS_CHANGED: 'Estado del expediente actualizado',
  JOB_CASE_REVIEW_STARTED: 'Revisión iniciada',
  CUSTOMER_INFORMATION_REQUESTED: 'Información solicitada al cliente',
  CUSTOMER_INFORMATION_RESPONDED: 'Cliente respondió información',
  MATERIAL_SPECIFICATION_DEFINED: 'Especificación de material definida',
  JOB_CASE_READY_FOR_QUOTATION: 'Expediente listo para cotizar',
  JOB_CASE_COMPLETED: 'Expediente completado',
  QUOTATION_CREATED: 'Cotización creada',
  QUOTATION_SENT: 'Cotización enviada',
  QUOTATION_ADJUSTMENT_REQUESTED: 'Cliente solicitó ajuste',
  QUOTATION_REVISION_CREATED: 'Revisión de cotización creada',
  QUOTATION_APPROVED: 'Cotización aprobada',
  QUOTATION_REJECTED: 'Cotización rechazada',
  QUOTATION_EXPIRED: 'Cotización vencida',
  QUOTATION_CANCELLED: 'Cotización cancelada',
  WORK_ORDER_CREATED: 'Orden de trabajo creada',
  WORK_ORDER_PLANNING_UPDATED: 'Planeación de OT actualizada',
  WORK_ORDER_DOCUMENT_PINNED: 'Documento fijado para fabricación',
  WORK_ORDER_CANCELLED: 'Orden de trabajo cancelada',
  ROUTING_SHEET_CREATED: 'Hoja de ruta creada',
  ROUTING_OPERATION_ADDED: 'Operación agregada a ruta',
  ROUTING_OPERATION_UPDATED: 'Operación de ruta actualizada',
  ROUTING_OPERATION_REMOVED: 'Operación retirada de ruta',
  ROUTING_SHEET_APPROVED: 'Hoja de ruta aprobada',
  ROUTING_SHEET_REOPENED: 'Hoja de ruta reabierta',
  ROUTING_SHEET_RELEASED: 'Hoja de ruta liberada',
  WORK_ORDER_RELEASED: 'Orden liberada a producción',
  PRODUCTION_STARTED: 'Producción iniciada',
  OPERATION_EXECUTION_STARTED: 'Operación iniciada',
  OPERATION_EXECUTION_COMPLETED: 'Operación completada',
  OPERATION_EXECUTION_CANCELLED: 'Operación cancelada',
  WORK_ORDER_MATERIAL_RECORDED: 'Consumo de material registrado',
  PRODUCTION_COMPLETED: 'Producción completada',
  QUALITY_HANDOFF: 'Orden enviada a calidad',
  WORK_ORDER_QUALITY_APPROVED: 'Calidad aprobada',
  WORK_ORDER_QUALITY_REJECTED: 'Calidad rechazada',
  QUALITY_INSPECTION_CREATED: 'Inspección creada',
  QUALITY_INSPECTION_STARTED: 'Inspección iniciada',
  QUALITY_MEASUREMENT_RECORDED: 'Medición registrada',
  QUALITY_MEASUREMENT_UPDATED: 'Medición actualizada',
  QUALITY_INSPECTION_APPROVED: 'Inspección aprobada',
  QUALITY_INSPECTION_REJECTED: 'Inspección rechazada',
  NON_CONFORMITY_OPENED: 'No conformidad abierta',
  NON_CONFORMITY_DETAILS_UPDATED: 'No conformidad actualizada',
  NON_CONFORMITY_REWORK_SELECTED: 'Retrabajo seleccionado',
  NON_CONFORMITY_SCRAP_RECORDED: 'Scrap registrado',
  NON_CONFORMITY_USE_AS_IS_AUTHORIZED: 'Uso tal cual autorizado',
  NON_CONFORMITY_CLOSED: 'No conformidad cerrada',
  WORK_ORDER_NC_RESOLVED: 'No conformidad de OT resuelta',
  REWORK_STARTED: 'Retrabajo iniciado',
  REWORK_COMPLETED: 'Retrabajo completado',
  REWORK_REINSPECTION_FAILED: 'Reinspección de retrabajo fallida',
  DELIVERY_CREATED: 'Entrega preparada',
  DELIVERY_DISPATCHED: 'Entrega despachada',
  DELIVERY_EVIDENCE_ATTACHED: 'Evidencia de entrega vinculada',
  DELIVERY_DELIVERED: 'Entrega confirmada',
  DELIVERY_CANCELLED: 'Entrega cancelada',
  WORK_ORDER_DELIVERED: 'Orden entregada',
}

export function getDashboardEventLabel(eventType: string): string {
  return eventLabels[eventType] ?? eventType.replaceAll('_', ' ').toLowerCase()
}

export function formatDashboardDateTime(value: string): string {
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return value

  return new Intl.DateTimeFormat('es-MX', {
    dateStyle: 'medium',
    timeStyle: 'short',
  }).format(date)
}
