package com.nocountry.qualitytrack.traceability.enums;

public enum TraceabilityEventType {
    REQUEST_SUBMITTED,
    JOB_CASE_CREATED,
    CUSTOMER_REQUEST_CANCELLED,
    DOCUMENT_ADDED,
    DOCUMENT_VERSION_ADDED,
    DOCUMENT_REMOVED,
    JOB_CASE_STATUS_CHANGED,
    JOB_CASE_REVIEW_STARTED,
    CUSTOMER_INFORMATION_REQUESTED,
    CUSTOMER_INFORMATION_RESPONDED,
    MATERIAL_SPECIFICATION_DEFINED,
    JOB_CASE_READY_FOR_QUOTATION
}
