package com.nocountry.qualitytrack.traceability.enums;

public enum TraceabilityActionType {
    VIEW_CUSTOMER_REQUEST,
    VIEW_JOB_CASE,
    VIEW_QUOTATION,
    VIEW_WORK_ORDER,
    VIEW_ROUTING_SHEET,
    VIEW_ROUTING_OPERATION,
    VIEW_OPERATION_EXECUTION,
    VIEW_DOCUMENT,
    VIEW_DOCUMENT_VERSION,
    VIEW_MATERIAL_LOT,
    VIEW_QUALITY_INSPECTION,
    VIEW_QUALITY_MEASUREMENT,
    VIEW_QUALITY_CHECK,
    VIEW_NON_CONFORMITY,
    VIEW_DELIVERY
}
