package com.nocountry.qualitytrack.shared.response;

public enum ApiSuccessCode {
    AUTH_REGISTERED,
    EMAIL_VERIFIED,
    VERIFICATION_EMAIL_SENT,
    AUTHENTICATED,
    PASSWORD_RESET_EMAIL_SENT,
    PASSWORD_RESET_COMPLETED,
    CUSTOMER_CREATED,
    CUSTOMER_RETRIEVED,
    CUSTOMER_UPDATED,
    CUSTOMER_MEMBERS_RETRIEVED,
    CUSTOMER_INVITATION_CREATED,
    CUSTOMER_INVITATIONS_RETRIEVED,
    CUSTOMER_INVITATION_RESOLVED,
    CUSTOMER_INVITATION_REGISTRATION_REQUIRED,
    CUSTOMER_INVITATION_ACCEPTED,
    CUSTOMER_INVITATION_REGISTRATION_COMPLETED
}
